Fix recursive parsers with inputs not named "s"
Not naming the input of a #[recursive_parser] function "s" would cause
an error like this:

  error[E0425]: cannot find value `s` in this scope
    --> nom-recursive/tests/test.rs:13:1
     |
  13 | #[recursive_parser]
     | ^^^^^^^^^^^^^^^^^^^ not found in this scope
     |

This fix properly uses #ident instead of hardcoded "s".